name: sync to gitee
on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-20.04

    steps:
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master

        with:
          src: github/ituknown
          dst: github/ituknown

          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}

          account_type: org

          clone_style: ssh

          # force_update: true

          static_list: ${{ github.event.repository.name }}
